CREATE TABLE configuration (
    id integer PRIMARY KEY,
    locale character varying(2),
    name character varying(255),
    type character varying(20),
    value character varying(255)
);

INSERT INTO configuration (id, name, type, locale, value) VALUES
(1, 'domain', NULL,'EN', 'http://www.mega-iq.com'),
(2, 'domain', NULL,'DE', 'http://de.mega-iq.com'),
(3, 'domain', NULL,'RU', 'http://ru.mega-iq.com'),
(4, 'title', 'PRACTICE_IQ', 'EN', 'title_PRACTICE_IQ'),
(5, 'title', 'PRACTICE_IQ', 'DE', 'title_PRACTICE_IQ'),
(6, 'title', 'PRACTICE_IQ', 'RU', 'title_PRACTICE_IQ'),
(7, 'title', 'STANDART_IQ', 'EN', 'title_STANDART_IQ'),
(8, 'title', 'STANDART_IQ', 'DE', 'title_STANDART_IQ'),
(9, 'title', 'STANDART_IQ', 'RU', 'title_STANDART_IQ'),
(10, 'title', 'MEGA_IQ', 'EN', 'title_MEGA_IQ'),
(11, 'title', 'MEGA_IQ', 'DE', 'title_MEGA_IQ'),
(12, 'title', 'MEGA_IQ', 'RU', 'title_MEGA_IQ'),
(13, 'title', 'MATH', 'EN', 'title_MATH'),
(14, 'title', 'MATH', 'DE', 'title_MATH'),
(15, 'title', 'MATH', 'RU', 'title_MATH'),
(16, 'title', 'GRAMMAR', 'EN', 'title_GRAMMAR'),
(17, 'title', 'GRAMMAR', 'DE', 'title_GRAMMAR'),
(18, 'title', 'GRAMMAR', 'RU', 'title_GRAMMAR'),
(19, 'email_subject_new_user', NULL,'EN', 'email_subject_new_user'),
(20, 'email_subject_new_user', NULL,'DE', 'email_subject_new_user'),
(21, 'email_subject_new_user', NULL,'RU', 'email_subject_new_user'),
(22, 'email_subject_email_verify', NULL,'EN', 'email_subject_email_verify'),
(23, 'email_subject_email_verify', NULL,'DE', 'email_subject_email_verify'),
(24, 'email_subject_email_verify', NULL,'RU', 'email_subject_email_verify'),
(25, 'email_subject_test_result', NULL,'EN', '{test_type_title} finished successfully'),
(26, 'email_subject_test_result', NULL,'DE', '{test_type_title} finished successfully'),
(27, 'email_subject_test_result', NULL,'RU', '{test_type_title} успешно пройден'),
(28, 'email_subject_forget', NULL,'EN', 'email_subject_forget'),
(29, 'email_subject_forget', NULL,'DE', 'email_subject_forget'),
(30, 'email_subject_forget', NULL,'RU', 'email_subject_forget'),
(31, 'email_subject_direct_login', NULL,'EN', 'email_subject_direct_login'),
(32, 'email_subject_direct_login', NULL,'DE', 'email_subject_direct_login'),
(33, 'email_subject_direct_login', NULL,'RU', 'email_subject_direct_login'),
(34, 'title_promo', 'PRACTICE_IQ', 'EN', 'title_promo_PRACTICE_IQ'),
(35, 'title_promo', 'STANDART_IQ', 'EN', 'title_promo_STANDART_IQ'),
(36, 'title_promo', 'MEGA_IQ', 'EN', 'title_promo_MEGA_IQ'),
(37, 'title_promo', 'MATH', 'EN', 'title_promo_MATH'),
(38, 'title_promo', 'GRAMMAR', 'EN', 'title_promo_GRAMMAR'),
(39, 'description', 'PRACTICE_IQ', 'EN', 'description_PRACTICE_IQ'),
(40, 'description', 'STANDART_IQ', 'EN', 'description_STANDART_IQ'),
(41, 'description', 'MEGA_IQ', 'EN', 'description_MEGA_IQ'),
(42, 'description', 'MATH', 'EN', 'description_MATH'),
(43, 'description', 'GRAMMAR', 'EN', 'description_GRAMMAR'),
(44, 'title_promo', 'PRACTICE_IQ', 'DE', 'title_promo_PRACTICE_IQ'),
(45, 'title_promo', 'STANDART_IQ', 'DE', 'title_promo_STANDART_IQ'),
(46, 'title_promo', 'MEGA_IQ', 'DE', 'title_promo_MEGA_IQ'),
(47, 'title_promo', 'MATH', 'DE', 'title_promo_MATH'),
(48, 'title_promo', 'GRAMMAR', 'DE', 'title_promo_GRAMMAR'),
(49, 'description', 'PRACTICE_IQ', 'DE', 'description_PRACTICE_IQ'),
(50, 'description', 'STANDART_IQ', 'DE', 'description_STANDART_IQ'),
(51, 'description', 'MEGA_IQ', 'DE', 'description_MEGA_IQ'),
(52, 'description', 'MATH', 'DE', 'description_MATH'),
(53, 'description', 'GRAMMAR', 'DE', 'description_GRAMMAR'),
(54, 'title_promo', 'PRACTICE_IQ', 'RU', 'title_promo_PRACTICE_IQ'),
(55, 'title_promo', 'STANDART_IQ', 'RU', 'title_promo_STANDART_IQ'),
(56, 'title_promo', 'MEGA_IQ', 'RU', 'title_promo_MEGA_IQ'),
(57, 'title_promo', 'MATH', 'RU', 'title_promo_MATH'),
(58, 'title_promo', 'GRAMMAR', 'RU', 'title_promo_GRAMMAR'),
(59, 'description', 'PRACTICE_IQ', 'RU', 'description_PRACTICE_IQ'),
(60, 'description', 'STANDART_IQ', 'RU', 'description_STANDART_IQ'),
(61, 'description', 'MEGA_IQ', 'RU', 'description_MEGA_IQ'),
(62, 'description', 'MATH', 'RU', 'description_MATH'),
(63, 'description', 'GRAMMAR', 'RU', 'description_GRAMMAR'),
(64, 'test_url', 'PRACTICE_IQ', NULL,'/iqtest/iq-practice'),
(65, 'test_url', 'STANDART_IQ', NULL,'/iqtest/iq-standard'),
(66, 'test_url', 'MEGA_IQ', NULL,'/iqtest/mega-iq'),
(67, 'test_url', 'MATH', NULL,'/iqtest/math'),
(68, 'test_url', 'GRAMMAR', NULL,'/iqtest/grammar'),
(69, 'test_pic', 'PRACTICE_IQ', NULL,'https://storage.googleapis.com/mega-iq/iqtest/bg-big-practice.jpg'),
(70, 'test_pic', 'STANDART_IQ', NULL,'https://storage.googleapis.com/mega-iq/iqtest/bg-big-standard.jpg'),
(71, 'test_pic', 'MEGA_IQ', NULL,'https://storage.googleapis.com/mega-iq/iqtest/bg-big-mega.jpg'),
(72, 'test_pic', 'MATH', NULL,'https://storage.googleapis.com/mega-iq/iqtest/bg-big-math.jpg'),
(73, 'test_pic', 'GRAMMAR', NULL,'https://storage.googleapis.com/mega-iq/iqtest/bg-big-grammar.jpg'),
(74, 'test_time', 'PRACTICE_IQ', NULL,'5'),
(75, 'test_time', 'STANDART_IQ', NULL,'10'),
(76, 'test_time', 'MEGA_IQ', NULL,'30'),
(77, 'test_time', 'MATH', NULL,'10'),
(78, 'test_time', 'GRAMMAR', NULL,'10'),
(79, 'test_questions', 'PRACTICE_IQ', NULL,'4'),
(80, 'test_questions', 'STANDART_IQ', NULL,'12'),
(81, 'test_questions', 'MEGA_IQ', NULL,'36'),
(82, 'test_questions', 'MATH', NULL,'12'),
(83, 'test_questions', 'GRAMMAR', NULL,'12'),
(84, 'message_start_test_fail', NULL,'EN', 'An error occurred while starting a test. Please try again later'),
(85, 'message_delete_success', NULL,'EN', 'Test result successfully deleted'),
(86, 'message_internal_error', NULL,'EN', 'Service error. Please try again later'),
(87, 'message_invalid_access', NULL,'EN', 'Access denied, Please log in and try again'),
(88, 'message_wrong_request', NULL,'EN', 'Wrong request'),
(89, 'message_start_test_fail', NULL,'RU', ''),
(90, 'message_delete_success', NULL,'RU', ''),
(91, 'message_internal_error', NULL,'RU', ''),
(92, 'message_invalid_access', NULL,'RU', ''),
(93, 'message_wrong_request', NULL,'RU', ''),
(94, 'message_start_test_fail', NULL,'DE', ''),
(95, 'message_delete_success', NULL,'DE', ''),
(96, 'message_internal_error', NULL,'DE', ''),
(97, 'message_invalid_access', NULL,'DE', ''),
(98, 'message_wrong_request', NULL,'DE', '');